DEL-368: Upload downtime reports to s3
integr8ly/delorean pull request #135
Opened 2020-08-27 10:15 UTC by StanleyKaleta

2020-08-27 11:37 UTC, wei-lee commented on cmd/queryReport.go
> +	reportCmd.AddCommand(cmd)
from the description of the commands, I think it's better to keep this command as a subcommand for `pipeline`. The reporting commands are mainly for importing data into Polarion or reportportal. Here we are still mainly about generating the report and upload to s3.

2020-08-27 11:38 UTC, wei-lee commented on cmd/queryReport.go
> +			awsSecretKey, err := requireValue(AWSSecretAccessKeyEnv)
these keys should only be required if the `s3bucket` flag is set. It should be possible to run the command without uploading the report.

2020-08-27 11:39 UTC, wei-lee commented on cmd/queryReport.go
> +			}))
this should only be needed when it is required to upload the report.

2020-08-27 11:47 UTC, wei-lee commented on cmd/queryReport.go
> +	err = utils.ZipFolder(zippedDir, zippedDir+c.zipFile)
there is no need to zip the folder here. There is only one file that needs to be uploaded. If you want to zip the files here, make sure you will need to unzip them [here](https://github.com/integr8ly/delorean/blob/master/cmd/datahubImport.go#L161)

2020-08-27 11:48 UTC, wei-lee requested changes
see my comments above

2020-08-27 14:31 UTC, StanleyKaleta commented on cmd/queryReport.go
> +	reportCmd.AddCommand(cmd)
ok

2020-09-03 15:21 UTC, StanleyKaleta commented on cmd/queryReport.go
> +	err = utils.ZipFolder(zippedDir, zippedDir+c.zipFile)
@wei-lee updated PR

2020-09-04 13:43 UTC, wei-lee commented
/retest

2020-09-04 13:44 UTC, wei-lee approved these changes

2020-09-04 13:45 UTC, wei-lee commented
/lgtm
/approve

2020-09-04 13:46 UTC, merged