Openshift CI Release update for RHOAM
integr8ly/delorean pull request #148
Opened 2020-10-15 11:14 UTC by Boomatang

These changes allow the use of a rhoam prefix to branch names.
Selectable by a input flag of --olmType. The default for the flag is integreatly-operator.
Images that are mirrored from prow has also been updated to suit the new install type.

**JIRA** https://issues.redhat.com/browse/MGDAPI-31

Sample out put which would be created in a pr to openshift/release can been seen here. https://github.com/Boomatang/release/pull/4
Command used to create the pr was. values for the upstream was changed to from the openshift/release to Boomatang/release. this was a hard code value change and has been reverted in this pr.
```
GITHUB_TOKEN=<TOKEN> GITHUB_USER="Boomatang" ./delorean release openshift-ci-release --version 99.999.999 -o Boomatang --olmType managed-api-service
```

2020-10-19 08:40 UTC, wei-lee commented on cmd/openshiftCIRelease.go
> +		releaseRepoInfoUpstream: &githubRepoInfo{owner: "Boomatang", repo: f.openshiftCIRepo},
need to revert the hardcode value to use the flags

2020-10-19 08:44 UTC, wei-lee commented on pkg/utils/rhmi_version.go
> +func NewRHMIVersion(version string, olmType string) (*RHMIVersion, error) {
it looks like the only place where `olmType` used is for the `ReleaseBranchName` method? if this is the case, then it might be a much smaller change if we update the `ReleaseBranchName` method to take in the `olmType` as an extra optional parameter, rather than adding it as a parameter to the constructor? It doesn't feel right to have the `olmType` as part of a version.

2020-10-19 08:46 UTC, wei-lee commented on pkg/utils/rhmi_version_test.go
> +			olmType:        "integrealy-operator",
consider using the constants you have already defined.

2020-10-19 08:47 UTC, wei-lee requested changes
Added a few comments. If this the only command that needs to be changed? Any other commands needs to be updated as well?

2020-10-19 13:37 UTC, Boomatang commented on cmd/openshiftCIRelease.go
> +		releaseRepoInfoUpstream: &githubRepoInfo{owner: "Boomatang", repo: f.openshiftCIRepo},
Will change

2020-10-19 13:45 UTC, Boomatang commented on pkg/utils/rhmi_version.go
> +func NewRHMIVersion(version string, olmType string) (*RHMIVersion, error) {
The initial work here was getting the Makefile for integreatly work for both rhmi and rhoam. Now that I have looked into the release pipeline there will be other functions that require the version to know about olm type. I am going to mark this pr as a WIP till I get the required updated to work with the pipeline in place. 
I understand the `olmType` seem wrong as part of the version. With the hindsight from looking into the release pipeline I feel putting it in the version will reduce the changes and check that would be required in other functions.

2020-10-19 13:45 UTC, Boomatang commented on pkg/utils/rhmi_version_test.go
> +			olmType:        "integrealy-operator",
While change

2020-10-19 13:46 UTC, Boomatang commented
It does look like other commands will need to be changed.

2020-10-19 14:00 UTC, wei-lee commented on pkg/utils/rhmi_version.go
> +func NewRHMIVersion(version string, olmType string) (*RHMIVersion, error) {
How so? do you have an example?

2020-10-19 14:38 UTC, Boomatang commented on pkg/utils/rhmi_version.go
> +func NewRHMIVersion(version string, olmType string) (*RHMIVersion, error) {
An example, sure. As part of the release the help repo is been tagged the same as the release branch. This https://github.com/integr8ly/delorean/blob/master/cmd/tagRepository.go#L80-L81 gets called each time and we need to update the tag style to suit for `rhoam` Same thing happens with pushing images to quay. 

On the other side of this I do want to keep rhmi as the default so we don't have to go back updated existing pipelines for rhmi. Because of this I think do the version prefixing is easiest done in the RHMIversion stuct.

2020-10-19 14:48 UTC, wei-lee commented on pkg/utils/rhmi_version.go
> +func NewRHMIVersion(version string, olmType string) (*RHMIVersion, error) {
Ok, fair enough. In this case I would suggest that to keep the existing `NewRHMIVersion` method, which will by default continue using `integreaty-operator` as the olmType, and create a new method that will take the `olmType` parameter. This way you only need to update files that you actually need to override the default `olmType`, rather than changing them everywhere.

2020-10-19 15:01 UTC, Boomatang commented on pkg/utils/rhmi_version.go
> +func NewRHMIVersion(version string, olmType string) (*RHMIVersion, error) {
That is such a better idea. I never liked it passing the `olmType` while the method was called `NewRHMIVersion`. I will make the new method called `NewVersion`

2020-10-20 18:34 UTC, laurafitzgerald reviewed
Just taking a quick look. I think it's still in progress. Just one question inline. I also spotted that all the image mapping files that we use in openshift/release are using the versions without the v. e.g. prow mirrors versions 2.0->2.7 in quay but the images we use inside the manifest directories are in the format v2.1.0. I think that means that we don't actually use the images mirrored by prow? This seems historical and not related to your change here as that seems to be following the others, in the case of the mirroring mapping file at least.

2020-10-20 18:34 UTC, laurafitzgerald commented on cmd/root.go
> +	releaseCmd.PersistentFlags().StringVarP(&olmType, "olmType", "", DefaultIntegreatlyOperatorRepo, "OLM type for the release. Valid inputs are \"integreatly-operator\" or \"managed-api-service\"")
I notice that we provide integreatly-operator as a default in the code and we specify here that valid input is either `integreatly-operator` or `managed-api-service`. I think this is mostly used by the pipeline but if someone runs the command with a typo in `managed-api-service` and it defaults to integreatly-operator is it just a case of running the command again correctly or does it handle a bad entry?

2020-10-21 08:21 UTC, Boomatang commented on cmd/root.go
> +	releaseCmd.PersistentFlags().StringVarP(&olmType, "olmType", "", DefaultIntegreatlyOperatorRepo, "OLM type for the release. Valid inputs are \"integreatly-operator\" or \"managed-api-service\"")
It does not validated for a bad entry. If a service is put in wrongly the default is to act like a its `integreatly-operator` Are you suggesting that we error out if an unknown olm type is passed in.

2020-10-21 14:54 UTC, philbrookes commented on cmd/root.go
> +	releaseCmd.PersistentFlags().StringVarP(&olmType, "olmType", "", DefaultIntegreatlyOperatorRepo, "OLM type for the release. Valid inputs are \"integreatly-operator\" or \"managed-api-service\"")
I suppose the result of bad input is a PR to MT right? Which we could close? At the same time, maybe errorring out is more sensible here, could be confusing trying to work out where your release has gone, when there were no errors for your typo.

2020-10-21 16:43 UTC, laurafitzgerald commented on cmd/root.go
> +	releaseCmd.PersistentFlags().StringVarP(&olmType, "olmType", "", DefaultIntegreatlyOperatorRepo, "OLM type for the release. Valid inputs are \"integreatly-operator\" or \"managed-api-service\"")
Yeah it's definitely not a hill I'm willing to die on. I think if we have time to do it now it would be nice or alternatively we could push it out to a new JIRA so as not to block this work being finished in the time.

2020-10-22 09:04 UTC, Boomatang commented on cmd/root.go
> +	releaseCmd.PersistentFlags().StringVarP(&olmType, "olmType", "", DefaultIntegreatlyOperatorRepo, "OLM type for the release. Valid inputs are \"integreatly-operator\" or \"managed-api-service\"")
Ok I will get a possible fix for this into it today

2020-10-22 09:15 UTC, philbrookes commented on cmd/root.go
> +	releaseCmd.PersistentFlags().StringVarP(&olmType, "olmType", "", DefaultIntegreatlyOperatorRepo, "OLM type for the release. Valid inputs are \"integreatly-operator\" or \"managed-api-service\"")
yeah agreed, as we're pretty time sensitive on this PR, I'm happy to resolve this later and just get this merged as is for now.

2020-10-22 10:08 UTC, Boomatang commented
/test format

2020-10-22 10:42 UTC, philbrookes commented
@Boomatang Can you rerun your test and confirm the output still looks OK? Can you also verify that the RHMI flow is unaffected?

2020-10-22 11:29 UTC, Boomatang commented
@philbrookes I reran my checks, found one spot which I was spelling integreatly wrong. That has now been forced pushed.

2020-10-22 11:49 UTC, philbrookes commented
/lgtm
/approve

2020-10-22 11:52 UTC, wei-lee commented on configurations/managed-tenants-addons-config-rhoam.yaml
> +              value: "{{ alertingEmailAddress }}"
I am pretty sure you don't need to put this in a separate file. You can add it to the existing configuration file. When the command runs it will look up for the right configuration using name.

2020-10-22 13:30 UTC, Boomatang commented on configurations/managed-tenants-addons-config-rhoam.yaml
> +              value: "{{ alertingEmailAddress }}"
You are possible correct. Would it possible to get this merged and I will make a new PR to remove it. Its just the MR to ci-cd has already been merged which is using this config file. So that would also need to be updated. And we would like to use this in a release run today

2020-10-22 13:54 UTC, wei-lee commented on configurations/managed-tenants-addons-config-rhoam.yaml
> +              value: "{{ alertingEmailAddress }}"
sure

2020-10-22 13:54 UTC, wei-lee commented
/lgtm
/approve

2020-10-22 13:59 UTC, merged