[WIP] mgdapi-304-initial changes
integr8ly/delorean pull request #173
Opened 2021-01-15 11:12 UTC by MStokluska

Changes related to https://issues.redhat.com/browse/MGDAPI-304

Do not merge - manifest generation script must be updated first

To verify changes:
Run from this repo
- make build/cli
- update the "DefaultIntegreatlyGithubOrg" to your github org in root.go file
- make sure that your local branch of integreatly operator is up to date
- generate new client access token
- export GITHUB_TOKEN=<YOUR ACCESS TOKEN>
- export GITHUB_USER=<YOUR USER NAME> 
- ./delorean release create-rhoam-manifest --version=1.1.0 --olmType=managed-api-service --branch=master

Verify that a new PR has been submitted against your branch with name `rhoam-manifest-for-release-rhoam-1.1.0`

2021-01-20 13:57 UTC, Boomatang reviewed
I know there is some changes coming so this is the first pass on it. This is only the code review I have not done any other steps. There maybe more need in the units but I will check that when I start running this local.

2021-01-20 13:57 UTC, Boomatang commented on cmd/createRhoamManifest.go
> +	manifestPath := fmt.Sprintf("%s/rhoam-manifests/%s", repoDir, manifestFileName)
If my first comment on the command rename is seen a valuable, these string would possible need to be created based on the olmType. Putting this comment as a marker.

2021-01-20 13:57 UTC, Boomatang commented on pkg/utils/rhmi_version.go
> +func (v *RHMIVersion) PrepareRhoamManifestBranchName() string {
This function should be more generic and switch the output depending on the olmType.

2021-01-20 13:57 UTC, Boomatang commented on cmd/createRhoamManifest.go
> +func checkoutBranch(repoWorkTree *git.Worktree, keepChanges bool, create bool, branchName string) error {
To me I feel this function may have been created before and if not should this be moved to pkg/utils

2021-01-20 13:57 UTC, Boomatang commented on cmd/createRhoamManifest_test.go
> +			description: "should successfully generate the correct manifest",
Do we need to check the generate of a manifest which has not changed

2021-01-20 14:02 UTC, MStokluska commented on cmd/createRhoamManifest.go
> +		Short: "Create a rhoam manifest of a given version",
this can change into `create-manifest`, however I think that `create-manifest` is too broad. As for the difference between rhmi and rhoam, reason why it is not checked is because it makes no difference. Go mod graph is called on the entire repo, not only rhoam related packages. If we ever decide to have a different manifest for rhmi production, all we would do is edit the script itself

2021-01-20 14:03 UTC, MStokluska commented on cmd/createRhoamManifest.go
> +	cmd.Flags().StringVarP(&f.baseBranch, "branch", "b", "master", "Base branch of the manifest generation")
"master" and the baseBranch from jenkins pipeline build, which is also called `baseBranch`

2021-01-20 15:57 UTC, Boomatang commented on cmd/createRhoamManifest.go
> +	cmd.Flags().StringVarP(&f.baseBranch, "branch", "b", "master", "Base branch of the manifest generation")
If this is the name that is coming from jenkins I am happy. To me it seems a bit vague of a description. I am right in saying this will be the branch any PR's would be create against when running the command.

2021-01-22 11:54 UTC, Boomatang requested changes
Mostly looks good, I do have a few question, comments and requests

2021-01-22 11:54 UTC, Boomatang commented on cmd/createProdsecManifest.go
> +	envs := []string{fmt.Sprintf("OLM_TYPE=%s", c.version.OlmType()), "TYPE_OF_MANIFEST=production", fmt.Sprintf("PATH=%s", os.Getenv("PATH")), "HOME=/tmp"}
`"TYPE_OF_MANIFEST=production"`, will there ever be a need for this to be anything else?

2021-01-22 11:54 UTC, Boomatang commented on cmd/createProdsecManifest.go
> +	if pr == nil {
Can we have a chat about this logic, I think we can improve the readability here a bit.

2021-01-22 11:54 UTC, Boomatang commented on cmd/createProdsecManifest.go
> +		Force:  keepChanges,
During the checkout of a branch what changes are you expected need to be kept? I don't think we need the `Force: keepChanges,`

2021-01-22 11:54 UTC, Boomatang commented on cmd/createProdsecManifest_test.go
> +			},
The verify function is the same in both cases expect the path to the manifest file. Is there anything we can do to tidy this up and not repeat code.

2021-01-22 11:54 UTC, Boomatang commented on cmd/createProdsecManifest_test.go
> +	cases := []struct {
I would like to see a test that checks what happens if manifest does not need updating and the PR is tried to be updated.

2021-01-22 11:54 UTC, Boomatang commented on pkg/utils/rhmi_version.go
> +func (v *RHMIVersion) PrepareProdsecManifestBranchName() string {
Can we add some unit tests for this function

2021-01-22 11:54 UTC, Boomatang commented on pkg/utils/rhmi_version.go
> +func (v *RHMIVersion) NameByOlmType() string {
Can we add some unit tests for this function

2021-01-22 14:21 UTC, MStokluska commented on cmd/createProdsecManifest.go
> +	envs := []string{fmt.Sprintf("OLM_TYPE=%s", c.version.OlmType()), "TYPE_OF_MANIFEST=production", fmt.Sprintf("PATH=%s", os.Getenv("PATH")), "HOME=/tmp"}
no, it's for production only.

2021-01-22 14:23 UTC, MStokluska commented on cmd/createProdsecManifest.go
> +		Short: "Create a production manifest of a given version and olm type",
It's the version you are aiming to promote to production

2021-01-22 15:17 UTC, MStokluska commented on cmd/createProdsecManifest.go
> +		Force:  keepChanges,
None really, it doesn't work exactly as if you would locally checkout branches. For example, if you checkout from release-1.1.0 to master, all differences are kept and master branch gets populated with release-1.1.0 data. Force: set to true forces any changes between branches to be excluded from branching.

2021-01-22 15:18 UTC, MStokluska commented on cmd/createProdsecManifest_test.go
> +			},
Not that I'm aware as they are cases, if you know of a way how could we move it into 1 case please let me know, although I think a case - should be unique with values hard coded to ensure that the particular case covers particular settings.

2021-01-22 15:21 UTC, MStokluska commented on pkg/utils/rhmi_version.go
> +func (v *RHMIVersion) PrepareProdsecManifestBranchName() string {
Do you think it is necessary as it's only a switch statement? Following the approach used so far, not creating unit test cases for simple functions that reside in rhmi_version.go I decided to skip it too.

2021-01-22 15:22 UTC, MStokluska commented on pkg/utils/rhmi_version.go
> +func (v *RHMIVersion) NameByOlmType() string {
Same as above, I think we are ok to skip unit tests of function that contains only switch statement with default value in worst case scenario.

2021-01-22 15:41 UTC, Boomatang commented on pkg/utils/rhmi_version.go
> +func (v *RHMIVersion) PrepareProdsecManifestBranchName() string {
If the function is simple it should be simple create the unit test. Delorean has a good unit test habit, we should try to maintain that good practice as best we can. And the fact it's in the rhmi_version.go file maybe a bigger reason to have the tests. Nearly every command uses the code from this file.

2021-01-22 15:42 UTC, Boomatang commented on pkg/utils/rhmi_version.go
> +func (v *RHMIVersion) NameByOlmType() string {
Same answer as above, it's about keeping the quaintly high for the next person making changes.

2021-01-22 15:44 UTC, Boomatang commented on cmd/createProdsecManifest.go
> +		Force:  keepChanges,
Ok I am happy with answer (I think) it seems a bit backwards

2021-01-22 15:46 UTC, Boomatang commented on cmd/createProdsecManifest_test.go
> +			},
It is the function been create inline on the verify step which can be refactored to be shared between both. Not the test case its self. I am happy with the two cases, would even like to see more.

2021-01-22 17:04 UTC, MStokluska commented on pkg/utils/rhmi_version.go
> +func (v *RHMIVersion) PrepareProdsecManifestBranchName() string {
thanks, updated!

2021-01-22 17:04 UTC, MStokluska commented on pkg/utils/rhmi_version.go
> +func (v *RHMIVersion) NameByOlmType() string {
thanks, updated!

2021-01-22 18:14 UTC, MStokluska commented on cmd/createProdsecManifest.go
> +	if pr == nil {
Resolving as per our conversation, so our main points out of this, delorean cli could use a slight refactor to 3 existing cli commands that use same functions, these functions should be made in utils to become shared functions. Also, as per our conversation, updating some unit tests would be useful. Thanks @Boomatang

2021-01-22 18:15 UTC, MStokluska commented on cmd/createProdsecManifest.go
> +		Force:  keepChanges,
Updated the "keepChanges" to be more of a reflection of what we are doing here.

2021-01-22 18:15 UTC, MStokluska commented on cmd/createProdsecManifest_test.go
> +			},
Good spot, thanks for helping me out with it.

2021-01-22 18:16 UTC, MStokluska commented on cmd/createProdsecManifest_test.go
> +	cases := []struct {
As per our conversation, we have agreed that in line what's done in other functions that use the similar function to create a release branch, this could be part in creating this function as shared in utils and then the appropriate test cases could be done. Thanks.

2021-01-22 18:18 UTC, MStokluska commented
Thanks for the review @Boomatang, we have run the verification against my own integreatly repo and it works as expected.

2021-01-25 11:37 UTC, Boomatang commented
/lgtm

2021-01-27 09:11 UTC, philbrookes commented
/approve

2021-01-27 09:12 UTC, laurafitzgerald commented
/approve

2021-01-27 09:19 UTC, merged