adding autoscale and sts options
integr8ly/delorean pull request #284
Opened 2022-09-19 12:25 UTC by laurafitzgerald

Adding options to expose  config for 
sts enabled
autoscaling
for rosa cluster creation

2022-09-19 12:29 UTC, cecobask commented on scripts/sts/sts.sh
>      sleep 30s
```suggestion
    sleep 30
```

This is a syntax error that I meant to fix. Can you include it with your changes, please?

2022-09-19 12:36 UTC, valerymo commented on scripts/sts/sts.sh
>      sleep 30s
30s seems good, and 30 also is good for sleep in bash ..

2022-09-19 13:02 UTC, valerymo commented
@laurafitzgerald This is not changed in this PR in ocm.mk, but seems seems need add "sts" here https://github.com/integr8ly/delorean/blob/638609693ec58d1144cf8d6d7783aa0e47b9fe17/make/ocm.mk#L86  
.PHONY: ocm/rhoam-prerequisites
ocm/sts/rhoam-prerequisites:
	@${STS_SH} rhoam-prerequisites

2022-09-19 13:53 UTC, valerymo commented on scripts/sts/sts.sh
> +CLUSTER_NAME="${CLUSTER_NAME:-default}}"
@laurafitzgerald  - there is extra "}" here, as a result - error in cluster creation (please see --cluster-name 'vm}' ): 
+ rosa create cluster --cluster-name 'vm}' --compute-nodes=4 --compute-machine-type=m5.xlarge --region=eu-west-1 --sts true --mode auto -y
E: Cluster name must consist of no more than 15 lowercase alphanumeric characters or '-',

2022-09-20 08:47 UTC, valerymo commented
Cluster created. Changes looks good for me. I had problem with 3scale installation on this cluster, but not sure it's related to changes in PR, so - /lgtm

2022-09-20 08:47 UTC, valerymo commented
/lgtm

2022-10-04 03:40 UTC, trepel commented on make/ocm.mk
The path should be scripts/rosa/rosa.sh

2022-10-04 15:07 UTC, trepel commented on make/ocm.mk
I tried the make command after fixing this and the cluster was created just fine.

2022-10-04 15:09 UTC, carlkyrillos reviewed
I was able to get it working after making a few tweaks to the script

2022-10-05 09:06 UTC, trepel commented on scripts/rosa/rosa.sh
> +    if [[ $STS_ENABLED == 'true' ]] then
cool, you already reported this (sorry, I forgot about that myself)

2022-10-05 14:40 UTC, carlkyrillos reviewed
Added one small comment but other than that I think it's ready!

2022-10-06 14:27 UTC, KevFan commented on scripts/rosa/rosa.sh
> +#  NODE_COUNT=4
```suggestion
#  NODES_COUNT=4
```

2022-10-06 14:31 UTC, KevFan requested changes
Looks good 👍  Have some minor comments 🧑‍💻

2022-10-06 14:31 UTC, KevFan commented on make/ocm.mk
>  .PHONY: ocm/rhoam-prerequisites
```suggestion
.PHONY: ocm/sts/rhoam-prerequisites
```

Minor, but lets fix this also while we're updating the makefile anyway 👍

2022-10-06 14:31 UTC, KevFan commented on scripts/rosa/rosa.sh
> +#  NODE_COUNT=4
```suggestion
#  NODES_COUNT=4
```
Reference as `NODES_COUNT` but maybe it should be `NODE_COUNT` at the other places 🤔

2022-10-06 14:31 UTC, KevFan commented on scripts/rosa/rosa.sh
> +# make ocm/rosa/cluster/create (optional <CLUSTER_NAME= > <AWS_REGION= > <NODE_COUNT= > <MACHINE_TYPE= > <ENABLE_AUTOSCALING=true/false > <STS_ENABLED=true/false >)
```suggestion
# make ocm/rosa/cluster/create (optional <CLUSTER_NAME= > <AWS_REGION= > < NODE_COUNT= > <MACHINE_TYPE= > <ENABLE_AUTOSCALING=true/false > <STS_ENABLED=true/false >)
```
Same on `NODES_COUNT`

2022-10-06 14:40 UTC, laurafitzgerald commented on scripts/rosa/rosa.sh
> +# make ocm/rosa/cluster/create (optional <CLUSTER_NAME= > <AWS_REGION= > <NODE_COUNT= > <MACHINE_TYPE= > <ENABLE_AUTOSCALING=true/false > <STS_ENABLED=true/false >)
Seems like those are used against the ocm/sts/rhoam-prerequisites target rather than the ocm/rosa/cluster/create target? 🤔

2022-10-07 08:41 UTC, cecobask commented on scripts/rosa/rosa.sh
> +# make ocm/rosa/cluster/create (optional <CLUSTER_NAME= > <AWS_REGION= > <NODE_COUNT= > <MACHINE_TYPE= > <ENABLE_AUTOSCALING=true/false > <STS_ENABLED=true/false >)
@austincunningham, that's correct. It's always better to specify the `ROLE_NAME` and `FUNCTIONAL_TEST_ROLE_NAME` environment variables to something that won't clash with IAM roles for existing clusters (if any)

2022-10-11 20:15 UTC, carlkyrillos commented on scripts/rosa/rosa.sh
>          rhoam-prerequisites)
```suggestion
        rhoam_prerequisites)
```
Need to change this line and the line below (it wouldn't let me comment on that line) to `rhoam_prerequisites` because its [entrypoint](https://github.com/integr8ly/delorean/pull/284/files#diff-24835738dda67c8b67bfbc5ce87276ef690466eb2da99d467504a09ee1760057R88) in the makefile was changed to use an `_`

2022-10-11 20:16 UTC, carlkyrillos commented on scripts/rosa/rosa.sh
>          rhoam-prerequisites)
```suggestion
        rhoam_prerequisites)
```
Need to change this line and the line below (it wouldn't let me comment on that line) to `rhoam_prerequisites` because its [entrypoint](https://github.com/integr8ly/delorean/pull/284/files#diff-24835738dda67c8b67bfbc5ce87276ef690466eb2da99d467504a09ee1760057R88) in the makefile was changed to use an `_`

2022-10-12 19:30 UTC, carlkyrillos commented on scripts/rosa/rosa.sh
>          rhoam-prerequisites)
This was changed to `sts_cluster_prerequisites` because these steps only need to be run for ROSA clusters with STS enabled.

2022-10-13 15:05 UTC, trepel commented
I have just managed to provision rosa clusters using this PR successfully. Both STS enabled and STS disabled

/lgtm

2022-10-14 08:02 UTC, trepel commented
The only minor change I would suggest is to replace `sts` with `rosa` in `provision_sts_cluster` and `delete_sts_cluster` - but not a blocker to lgtm and approval to me.

2022-10-14 09:24 UTC, trepel commented
Cool, thanks for that naming convention improvements. I triggered the rosa STS provisioning just fine. At this stage I don't think it is needed to wait for it to complete since it was tested yesterday.

/lgtm
/approve

2022-10-14 09:40 UTC, merged