[WIP ]MGDAPI-5766 - script to pull the data from a cluster
integr8ly/delorean pull request #319
Opened 2023-05-31 12:57 UTC by valerymo

https://issues.redhat.com/browse/MGDAPI-5766

2023-06-06 13:47 UTC, Boomatang requested changes
If there is more than on tenant the script does execute correctly due to the number of admin urls. The access token for the API will only work on the default tenant. This means the stats from other tenants is not found. 

Not all clusters will have tenants defined by CR, the script should allow for both. 

I have not checked the developer portal counts are working correctly. I was using an non CCS cluster.

2023-06-06 13:47 UTC, Boomatang commented on scripts/delorean/get-cluster-data.sh
> +threescale_url=$(oc get route -n redhat-rhoam-3scale |grep admin |awk '{print $2}')
If there are multiply tenants this returns a list, which causes failures later in the script.

2023-06-06 13:47 UTC, Boomatang commented on scripts/delorean/get-cluster-data.sh
> +threescale_access_token=$(oc get secret system-seed -oyaml -n redhat-rhoam-3scale |grep ADMIN_ACCESS_TOKEN |awk '{print $2}' |base64 -d)
This access token only return the data from the default tenant. If there is more than one tenant the backends and products will not be recorded.

2023-06-06 13:47 UTC, Boomatang commented on scripts/delorean/get-cluster-data.sh
> +count=$(oc get Tenants --all-namespaces |wc  -l)
Tenants could have being created through the UI before the declarctive CR work was introduced in 3scale. If the case there would be no Tenant CR's. All so the default tenant does not have a CR.

2023-06-06 13:47 UTC, Boomatang commented on scripts/delorean/get-cluster-data.sh
> +
Would be nice to log the user and server output from the oc whoami. It would help with linking stats to a cluster.

2023-06-08 09:24 UTC, valerymo commented on scripts/delorean/get-cluster-data.sh
> +threescale_url=$(oc get route -n redhat-rhoam-3scale |grep admin |awk '{print $2}')
Fixed. this url now - only for admin
Thank you

2023-06-08 09:29 UTC, valerymo commented on scripts/delorean/get-cluster-data.sh
> +count=$(oc get Tenants --all-namespaces |wc  -l)
Thank you for comment. Changed. Tenants now calculated as accounts, using 3scale API

2023-06-08 13:47 UTC, closed without merging

2023-06-08 13:48 UTC, valerymo commented
Closing this PR, as was decided to move the script into integreately_help. 
This is new request/MR: https://gitlab.cee.redhat.com/rhcloudservices/integreatly-help/-/merge_requests/904/diffs